name: audrey
favicon: null
layout_spectrum: 0.8146689729765058
typography_spectrum: 0.6337872655130923
title: Audrey Simpson-Campbell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1658072154968977
  lightness: 0.5844707263167948
  saturation: 0.8124900790862739
  rhythmicContrast: 0.2606674067210406
purpose: []
